### ISSUE TITLE
Step fails on Bitrise

### ISSUE THREAD

**Issue by adamdunaiOTP** [thefuntasty/bitrise-step-apk-info#19]
Step ID: apk-info
Version: 1.4.6
Status: Failed

`exit status 15 (exit code: 15)`

log:
```
Fetching gem metadata from https://rubygems.org/.
Updating bundler to 4.0.0.beta1.
Fetching bundler 4.0.0.beta1
Installing bundler 4.0.0.beta1
Fetching gem metadata from https://rubygems.org/.
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle updated!
The `--without` flag has been removed because it relied on being remembered
across bundler invocations, which bundler no longer does. Instead please use
`bundle config set without 'test'`, and stop using this flag
```

**Comment by adamdunaiOTP** [comment]
pull request: https://github.com/futuredapp/bitrise-step-apk-info/pull/20

**Comment by adamhongmy** [comment]
For those who are like me looking for a workaround while waiting for the PR to be merged. 
You can temporary use the patched step from the [repo by the PR's author](https://github.com/SerhiiKaplun/bitrise-step-apk-info) by modifying your bitrise workflow's yaml file. 

Example as below:
```
workflows:
  Extract-App-Info:
    steps:
    - apk-info@1:
        is_skippable: true
    - git::https://github.com/SerhiiKaplun/bitrise-step-apk-info.git:
        title: APK Info Temp
```
See more on how to modify your yaml file [here](https://support.bitrise.io/en/articles/9676732-customizing-the-function-of-a-bitrise-step) 

Hope this helps anyone.

**Comment by SumeraMartin** [comment]
I published a new version. Can someone try whether it was published correctly and whether it is working now?

**Comment by adamhongmy** [comment]
Hey @SumeraMartin , I would like to test but my workflow uses both this and [bitrise-step-ipa-info](https://github.com/futuredapp/bitrise-step-ipa-info) which have the [same issue](https://github.com/futuredapp/bitrise-step-ipa-info/issues/5).  
Could you able to patch that too so that I can test both at once to save my credits  🙏🏻

**Comment by SumeraMartin** [comment]
@adamhongmy 1.1.1 is released there also

**Comment by adamhongmy** [comment]
I am still seeing the previous version on both apk (1.4.6) and ipa (1.1.0) steps. Even I set the version to "always latest". Maybe we have to wait for the update to fully roll out?

**Comment by SumeraMartin** [comment]
My naive hope that a webhook would automatically handle the new release version didn’t work. @radimvaculik  do you remember how we used to release this?

**Comment by skywall** [comment]
@SumeraMartin You have to create PR with new changes in [BitriseStepLib repo](https://github.com/bitrise-io/bitrise-steplib) (it is done via BitriseCLI tool).

How to: https://docs.bitrise.io/en/bitrise-ci/workflows-and-pipelines/developing-your-own-bitrise-step/sharing-steps-with-all-bitrise-users.html

**Comment by anthony-stephan-guilloteau** [comment]
Hello @SumeraMartin, can you provide us an ETA for the BitriseStepLib publication? 🙏 thank you so much in advance!

**Comment by anthony-stephan-guilloteau** [comment]
For those who are still waiting for the publication - here is another workaround, you can force the version 1.4.4
`    - apk-info@1.4.4: {}`

**Comment by SumeraMartin** [comment]
Working on this today, sorry for the delay

**Comment by SumeraMartin** [comment]
Merge requests for both libraries are created and waiting for approval. However, according to release manual we are missing these two things:

- I have a test for my Step, which can be run with bitrise run test (in the step's repository)
- I did run bitrise run audit-this-step (in the step's repository - note, if you don't have this workflow in your bitrise.yml, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)

but I will have time to add this no sooner then in the following days. So if any of you could update libraries with these step it then it would be great.

https://github.com/bitrise-io/bitrise-steplib/pull/4717
https://github.com/bitrise-io/bitrise-steplib/pull/4718
